FROM nginx

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx/nginx.conf /etc/nginx
COPY color_diary_project/static /var/www/static

RUN mkdir -p /var/www/
RUN chown $ID:$ID -R /var/www

CMD sed -i -e 's/user www-data;//g' /etc/nginx/nginx.conf && \
    sed -i -e 's/listen 80;/'"listen $PORT;"'/g' /etc/nginx/nginx.conf && \
    sed -i -e 's/back/127.0.0.1/g' /etc/nginx/nginx.conf && \
    nginx -g 'daemon off;'