version: '3.9'

volumes:
  static.volume:
    name: static.volume

services:

  back:
    build:
      context: .
      dockerfile: ./back/Dockerfile.back
    container_name: emotebook.back
    command: /bin/bash ./start_django.sh
    volumes:
      - static.volume:/code/color_diary_project/static
    expose:
      - 8000
    depends_on:
      - db
  
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile.nginx
    container_name: emotebook.nginx
    ports:
      - $PORT:80
    volumes:
      - static.volume:/var/www/static
    depends_on:
      - back
    environment:
      - PORT