# Generated by Django 3.1.4 on 2021-01-21 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('color_diary', '0004_auto_20210121_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['-hex_color', 'id']},
        ),
    ]
