# Generated by Django 3.1.4 on 2021-01-30 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('color_diary', '0005_auto_20210121_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['hex_color', 'id']},
        ),
    ]
