# Generated by Django 3.1.4 on 2021-01-30 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('color_diary', '0006_auto_20210130_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={},
        ),
    ]
