FROM nginx

RUN rm /etc/nginx/conf.d/default.conf

COPY ./nginx/nginx.conf /etc/nginx
COPY color_diary_project/static /var/www/static

RUN mkdir -p /var/www/
RUN chown www-data:www-data -R /var/www

CMD sed -i -e 's/listen 80;/'"listen $PORT;"'/g' /etc/nginx/nginx.conf && nginx -g 'daemon off;'